### ISSUE TITLE
add to readme how to install and how to run the app

### ISSUE THREAD

**Issue by shadiakiki1986** [SSOC18/quickfix-tradeclient-django#1]

**Comment by shadiakiki1986** [comment]
What's the point of having the first `webui` folder? The way I see it, you can easily move all that is in the 1st `webui` folder to the root folder, i.e. `manage.py` and `README.md` would be at the same level. Make sure to update your README section that says `navigate to webui and launch runserver`

**Comment by MickMek** [comment]
Changed folder set up, and screenshots below:

url `../form/` gives a form for users to input desired information for a trade with our quickfix tradeclient:
<img width="414" alt="screen shot 2018-08-09 at 12 14 27 pm" src="https://user-images.githubusercontent.com/40487507/43889986-39d01654-9bce-11e8-8515-2bb320bfa563.png">

url `../form/plotly` is a scatterplot with dummy data:
<img width="1280" alt="screen shot 2018-08-09 at 12 14 54 pm" src="https://user-images.githubusercontent.com/40487507/43890022-4ea04b8a-9bce-11e8-9f8a-f6b5ea065152.png">

**Comment by shadiakiki1986** [comment]
LGTM with regards to folder structure, but it seems you commited the `db.sqlite3` database file.

This is usually a sensitive issue, especially if it contains confidential data.

Can you please remove this file from all the git commit history? I think I had given you a pointer in an earlier issue about how to go about this. Let me know if you get stuck on this

**Comment by shadiakiki1986** [comment]
btw, the ssoc18.teamshadi.net server already had the necessary packages for this, but you don't include in your README what is needed for a fresh install. For example, you will at least need `pip install Django matplotlib`. Please list your project dependencies so that a fresh install can be made following the instructions in your readme

**Comment by MickMek** [comment]
Done, but had to delete whole commit history as the db.sqlite3 was in several commits with other critical improvements.
