### ISSUE TITLE
add a view for a scatter plot of two pandas Series (~2h)

### ISSUE THREAD

**Issue by shadiakiki1986** [SSOC18/quickfix-tradeclient-django#2]
Here's some sample code to put in `views.py` (I copy-pasted it from working code, and removed some undefined variables, but it may have errors)

```
import matplotlib
matplotlib.use('Agg')
from matplotlib import pyplot as plt
from matplotlib.backends.backend_agg import FigureCanvasAgg
from django.http import HttpResponse
import io
def productbasic_plot(request, pk):
    # plot main sample
    df_sub_main = pd.DataFrame({0:[1,2,3], 1: [4,5,6]})
    plt.scatter(df_sub_main[0], df_sub_main[1], label='sample', color='blue', alpha=.5)

    # general
    plt.title('scatter plot highlighting sample: %s'%("foo")))
    plt.legend()

    # https://stackoverflow.com/a/49544179/4126114
    canvas = FigureCanvasAgg(fig)
    buf = io.BytesIO()
    plt.savefig(buf, format='png')
    # close, as per https://stackoverflow.com/a/1874740/4126114
    plt.close(fig)

    response = HttpResponse(buf.getvalue(), content_type='image/png')
    return response
```

You will also need to define a route in `urls.py`

**Comment by MickMek** [comment]
scatter plot added to url .../form/plot

**Comment by shadiakiki1986** [comment]
Ok. Can you spend another hour to add another view for the same plot using
plotly (offline)?

**Comment by MickMek** [comment]
Using `plotly`, I was able to plot it on another tab, but with an error (no http response on original site)
` url ../form/plotly `
Unable to run it on server, needs `plotly` installed

**Comment by shadiakiki1986** [comment]
Can you test locally by the time I install it for you?

**Comment by MickMek** [comment]
yes no problem, working locally for now

**Comment by shadiakiki1986** [comment]
did the idea we spoke about on the phone work?

**Comment by MickMek** [comment]
yes, was able to use the function `render_to_response()` to upload `temp-plot.html`
However, the `offline.plot()` is required to update `temp-plot.html`, but it also opens up a new tab

latest commit will show the scatterplot with no error on the site, but opens another tab with the same scatter plot

**Comment by MickMek** [comment]
I have also tried to use this code, but got an authentication error:

```
	figure = go.Figure(data=data, layout=layout)
	py.image.save_as(figure, filename='temp-plot.png')
	image = Image('temp-plot.png')
	response = HttpResponse(image, content_type='image/png')
	return response
```

**Comment by shadiakiki1986** [comment]
It would be a good idea to post a few screenshots in the README showing the different pages of this application

**Comment by shadiakiki1986** [comment]
btw the screenshots you posted in https://github.com/SSOC18/quickfix-tradeclient-django/issues/1#issuecomment-411693956 should really go in the readme instead of in the issue

**Comment by MickMek** [comment]
fixed
